##
# deploy wiresafe/riot-web with kubernetes in gke
# - namespace: chat
# - deployment: chat
# - service: chat
# - ingress: chat.wiresafe.com -> svc/chat -> deploy/chat
## 
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: chat
  namespace: chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: chat
    spec:
      containers:
      - image: gcr.io/wiresafe-project/riot-web-wiresafe-prod:latest
        name: chat
        ports:
        - containerPort: 80
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: chat
  namespace: chat
  labels:
    app: chat
spec:
  ports:
  - port: 80
    name: http
    targetPort: http
  selector:
    app: chat
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chat
  namespace: chat
  annotations:
    kubernetes.io/ingress.global-static-ip-name: chat-wiresafe-com
    kubernetes.io/ingress.class: "gce"
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: true
spec:
  tls:
  - secretName: chat-tls
    hosts:
    - chat.wiresafe.com
  backend:
    serviceName: chat
    servicePort: http
  rules:
  - host: chat.wiresafe.com
    http:
        paths:
        - backend:
            serviceName: chat
            servicePort: http
