kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo-identity-config
  namespace: matrix
spec:
  storageClassName: standard
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo-identity-var
  namespace: matrix
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
