##
# deploy wiresafe/riot-web with Kubernetes in gke
##
---
##
# Namespace: riot-prod
##
kind: Namespace
apiVersion: v1
metadata:
  name: riot-prod
---
##
# deployment: riot-prod/riot
##
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: riot
  namespace: riot-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: riot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: riot
    spec:
      containers:
      - image: gcr.io/wiresafe-project/riot-web-wiresafe-prod:latest
        name:  riot-prod
        ports:
        - containerPort: 80
          name: http
---
##
# service: riot-prod/riot
##
apiVersion: v1
kind: Service
metadata:
  name: riot
  namespace: riot-prod
  labels:
    app: riot
spec:
  selector:
    app: riot
  type: NodePort
  ports:
  - port: 80
    name: http
    targetPort: http
---
##
# ingress: riot-prod/riot
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: riot
  namespace: riot-prod
  annotations:
    kubernetes.io/ingress.global-static-ip-name: chat-wiresafe-com
    kubernetes.io/tls-acme: "true"
    ingress.kubernetes.io/force-ssl-redirect: true
spec:
  tls:
  - secretName: chat-wiresafe-com-tls
    hosts:
    - chat.wiresafe.com
  backend:
    serviceName: riot
    servicePort: http
  rules:
  - host: chat.wiresafe.com
    http:
        paths:
        - backend:
            serviceName: riot
            servicePort: http
