kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo-disk
  namespace: matrix
  labels:
    app: matrix
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: matrix
  name: neo-config
  labels:
    app: matrix
spec:
  storageClassName: standard
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
