kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo-disk
  namespace: matrix
spec:
  gcePersistentDisk:
    pdName: neo-disk
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: neo-identity-disk
  namespace: matrix
spec:
  gcePersistentDisk:
    pdName: neo-identity-disk
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
