kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: neo-identity-disk
  namespace: matrix
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: matrix
  name: neo-identity-config
spec:
  storageClassName: standard
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
