kind: Deployment
apiVersion: apps/v1beta1
metadata:
  namespace: matrix
  name: matrix
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: matrix
      labels:
        app: matrix
      name: matrix
      generateName: matrix
    spec:
      volumes:
      - name: neo-disk
        persistentVolumeClaim:
          claimName: neo-disk
#      - name: neo-config
#        persistentVolumeClaim:
#          claimName: neo-config
#          readOnly: true
      containers:
      - name: matrix
        image: gcr.io/wiresafe-project/matrix:latest
        env:
        - name: SERVER_NAME
          value: "neo.wiresafe.com"
        - name: REPORT_STATS
          value: "yes"
        ports:
        - containerPort: 8008
          name: http
        volumeMounts:
        - name: neo-disk
          mountPath: /data
#        - name: neo-config
#          mountPath: /var/lib/matrix/neo
        readinessProbe:
          httpGet:
            path: /_matrix/client/versions
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 10
