kind: Deployment
apiVersion: apps/v1beta1
metadata:
  namespace: matrix
  name: matrix
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: matrix
      labels:
        app: matrix
    spec:
      volumes:
      - name: neo-disk
        gcePersistentDisk:
          pdName: neo-disk
      containers:
      - name: matrix
        image: gcr.io/wiresafe-project/matrix:latest
        env:
        - name: SERVER_NAME
          value: "neo.wiresafe.com"
        - name: REPORT_STATS
          value: "yes"
        ports:
        - containerPort: 8008
          name: http
        volumeMounts:
        - mountPath: /data
          name: neo-disk
        readinessProbe:
          httpGet:
            path: /_matrix/client/versions
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 10
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  namespace: matrix
  name: matrix-identity
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: matrix
      labels:
        app: matrix-identity
    spec:
      volumes:
      - name: neo-identity-disk
        gcePersistentDisk:
          pdName: neo-identity-disk
      - name: firebase-secrets
        secret:
          secretName: neo-identity-service-account
      containers:
      - name: matrix-identity
        image: gcr.io/wiresafe-project/matrix-identity:0.0.5
        ports:
        - containerPort: 8090
          name: http
        volumeMounts:
        - mountPath: /data
          name: neo-identity-disk
        - mountPath: /etc/firebase
          name: firebase-secrets
          readOnly: true
        readinessProbe:
          httpGet:
            path: /_matrix/identity/status
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 10
