apiVersion: v1
kind: Service
metadata:
  name: matrix-identity
  namespace: matrix
  labels:
    app: matrix-identity
    role: identity-server
spec:
  ports:
  - port: 8090
    targetPort: 8090
  selector:
    role: identity-server
  type: NodePort
